version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "scratch-render"
      - dependency-name: "scratch-vm"
      - dependency-name: "scratch-paint"
      - dependency-name: "scratch-svg-renderer"
      - dependency-name: "scratch-blocks"
      - dependency-name: "scratch-l10n"
