language: node_js
sudo: required
dist: xenial
addons:
    chrome: stable
node_js:
- 10
env:
  global:
  - CHROMEDRIVER_VERSION=LATEST
  - NODE_ENV=production
  - NODE_OPTIONS=--max-old-space-size=7250
  - NPM_TAG=latest
cache:
  directories:
  - node_modules
before_install:
# package-lock.json was introduced in npm@5
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
install:
- npm --production=false install
- npm --production=false update
script:
- npm run test:lint
- npm run test:unit
- npm run clean && npm run setup-opal && $(npm bin)/webpack --colors --bail --silent
- npm run test:integration
deploy:
- provider: script
  on:
    branch:
    - develop
  skip_cleanup: true
  script: npm run deploy -- -x -r https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
