language: node_js
sudo: required
dist: trusty
addons:
    chrome: stable
node_js:
- 8
env:
  - NODE_ENV=production
cache:
  directories:
  - node_modules
install:
- npm --production=false install
- npm --production=false update
before_deploy:
- npm --no-git-tag-version version 0.1.0-prerelease.$(date +%Y%m%d%H%M%S)
- git config --global user.email $(git log --pretty=format:"%ae" -n1)
- git config --global user.name $(git log --pretty=format:"%an" -n1)
deploy:
- provider: script
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH != master
  skip_cleanup: true
  script: npm run deploy -- -x -e $TRAVIS_BRANCH -r https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
- provider: script
  on:
    branch: master
  skip_cleanup: true
  script: npm run --silent deploy -- -x -a -r https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
- provider: npm
  on:
    branch:
    - master
    - develop
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
- provider: s3
  on:
    branch:
    - master
    - $PREVIEW_BRANCH
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET_NAME
  acl: public_read
  detect_encoding: true
  skip_cleanup: true
  local_dir: build
after_deploy:
- 'curl -X POST -H "Fastly-Key: $FASTLY_TOKEN" -H "Accept: application/json" https://api.fastly.com/service/$FASTLY_SERVICE_ID/purge_all'
